jenkinsslave1:
  name: jenkinsslave1
  image: evarga/jenkins-slave
jenkinsdockerslave1:
  name: jenkinsdockerslave1
  build: jenkinsdockerslave
  volumes:                                                                                                                                                                    
    - /var/run/docker.sock:/var/run/docker.sock                                                                                                                               
    - /var/lib/docker:/var/lib/docker           
jenkins:
  image: jenkins
  name: jenkins
  ports:
    - "8080:8080"
  links:
    - jenkinsslave1
    - jenkinsdockerslave1
jenkinssetup:
  name: jenkinssetup
  build: jenkinssetup
  links:
    - jenkins
jenkinscli:
  name: jenkinscli
  build: jenkinscli
  links:
    - jenkins

