jenkinsslave1:
  container_name: jenkinsslave1
  image: evarga/jenkins-slave
jenkinsdockerslave1:
  container_name: jenkinsdockerslave1
  build: jenkinsdockerslave
  volumes:                                                                                                                                                                    
    - /var/run/docker.sock:/var/run/docker.sock                                                                                                                               
    - /var/lib/docker:/var/lib/docker           
jenkins:
  build: jenkins
  container_name: jenkins
  ports:
    - "8080:8080"
  links:
    - jenkinsslave1
    - jenkinsdockerslave1
  volumes:                                                                                                                                                                    
    - /var/run/docker.sock:/var/run/docker.sock                                                                                                                               
    - /var/lib/docker:/var/lib/docker           
jenkinssetup:
  container_name: jenkinssetup
  build: jenkinssetup
  links:
    - jenkins
