jenkinsslave1:
  container_name: jenkinsslave1
  build: jenkinsslave1
jenkins:
  build: jenkins
  container_name: jenkins
  ports:
    - "8080:8080"
  links:
    - jenkinsslave1
jenkinssetup:
  container_name: jenkinssetup
  build: jenkinssetup
  links:
    - jenkins
